name: clickup_fading_scroll
description: Add a fading effect when the user can scroll.
version: 0.0.1
homepage: https://github.com/clickup/fading_scroll

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0